
services:
  web:
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_MANAGEPY_COLLECTSTATIC=on
      - DJANGO_MANAGEPY_CREATE_SUPERUSER=on

    build:
      context: .
      cache_from:
        - "${WEB_IMAGE}"

    image: "${WEB_IMAGE}"
    container_name: web
    restart: always
    command: gunicorn core.wsgi:application --timeout 60 --bind 0.0.0.0:8000
    
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - backend

  nginx:
    environment:
      - DJANGO_MANAGEPY_MIGRATE=off
      - DJANGO_MANAGEPY_COLLECTSTATIC=off
      - DJANGO_MANAGEPY_CREATE_SUPERUSER=off
    build:
      context: ./deployment/nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    container_name: nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    networks:
      - backendnet
    depends_on:
      - web
    mem_limit: 1g
  
volumes:
  static_volume:
  media_volume:

networks:
  backendnet:
    driver: bridge
